spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product_manager?useSSL=false
    username: root
    password: Jgd@9608
    driver-class-name: com.mysql.cj.jdbc.Driver

  #JPA Settings

  jpa:
    hibernate:
      ddl_auto:
        create
    show-sql: true

  server:
    port: 8081

